# Generated by Django 2.0.2 on 2018-02-22 19:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{12}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(choices=[('MBBS', 'MBBS'), ('SPC', 'Specialist'), ('OTR', 'Other')], default=1, max_length=4)),
                ('qual_add_info', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('practice_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('area_of_practice', models.TextField(max_length=100)),
                ('mobile_no', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\d{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('query_start_time', models.DateTimeField(blank=True)),
                ('needReply', models.BooleanField(default=True)),
                ('resolved', models.BooleanField(default=False)),
                ('satisfaction', models.IntegerField(blank=True, choices=[(1, 'Unsatisfactory'), (2, 'Moderately Satisfied'), (3, 'Satisfied')], null=True)),
                ('expert_assigned', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('reply_extra', models.TextField(blank=True, default=None, null=True)),
                ('reply_datetime', models.DateTimeField(blank=True, null=True)),
                ('expert', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Expert')),
                ('query', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Query')),
            ],
        ),
    ]
