# Generated by Django 2.0.3 on 2018-03-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='last_used',
            field=models.BooleanField(default=False),
        ),
    ]
