# Generated by Django 2.0.3 on 2018-03-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_expert_last_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expert',
            old_name='last_used',
            new_name='last_chosen',
        ),
    ]
