# Generated by Django 3.0.8 on 2020-07-25 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_query_satisfaction_link_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='query',
            name='needReply',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='resolved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='satisfaction_link_is_alive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
